### ISSUE TITLE
Thank you for your reply. This is my feedback. 

### ISSUE THREAD

**Issue by hamadi1** [guigolab/lncATLAS#2] opened 2017-12-29 00:41 UTC
Dear David, Thank you for your response. I can confirm that nothing happens when I type a gene name on the text box. I am using the front page to obtain the plots. I tried with google chrome and internet explorer many times but it doesn't work. Furthermore, I should mention that it takes long time to get access to the website. It looks that there is a server problem as well. I am living in South Korea. Please tell me how to solve this issue. Thank you. Best regards.

**Comment by davidmasp** [comment] 2018-01-09 09:33
Duplicate of #1

**Closed as completed by davidmasp** 2018-01-09 09:33 UTC

**Comment by jliz85** [comment] 2019-05-09 09:34
I am encountering exactly the same issue.
Bests, 
Julia
